(()=>{'use strict';
const projects=[{id:'bathroom',title:'Bathroom refresh',detail:'Panelling & painting',note:'From a blank wall to a room with character.',source:'https://www.facebook.com/photo.php?fbid=1611392387663830',original:'bathroom.jpg'},{id:'garden',title:'Garden tidy-up',detail:'Home & garden maintenance',note:'A little care. Room to enjoy the garden again.',source:'https://www.facebook.com/photo.php?fbid=1624609679675434',original:'garden.jpg'}];
const board=document.createElement('section');board.className='project-board';board.setAttribute('aria-labelledby','board-title');board.hidden=true;
const cards=projects.map((p,i)=>`<button class="project-print print-${i}" data-project="${p.id}" aria-label="View ${p.title} before and after"><span class="paper-tape" aria-hidden="true"></span><span class="photo-pair"><span><img src="assets/projects/${p.id}-before.jpg" alt="${p.title} before the work" loading="lazy" width="520" height="620"><b>Before</b></span><span><img src="assets/projects/${p.id}-after.jpg" alt="${p.title} after the work" loading="lazy" width="520" height="620"><b>After</b></span></span><span class="print-caption"><strong>${p.title}</strong><small>${p.detail}</small><span class="view-mark" aria-hidden="true">↗</span></span></button>`).join('');
board.innerHTML=`<header class="board-heading"><span class="board-kicker">Pinned from the workbench</span><h2 id="board-title">A little work.<br><em>A big difference.</em></h2><p>Real homes. Real transformations.<br>A few of the jobs we're proud of.</p><svg class="pencil-mark" viewBox="0 0 130 34" aria-hidden="true"><path d="M4 19 Q50 6 124 14 M12 26 Q66 18 113 23" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg></header><div class="project-prints">${cards}</div><footer class="board-footer"><span>Repairs · Maintenance · Improvements</span><a href="https://www.facebook.com/profile.php?id=100063792536195" target="_blank" rel="noopener noreferrer">More from Hester ↗</a></footer>`;
document.body.append(board);document.body.append(document.querySelector(".note"));
const dialog=document.createElement('dialog');dialog.className='project-dialog';dialog.setAttribute('aria-labelledby','project-title');dialog.innerHTML=`<button class="photo-close" aria-label="Close project photos">×</button><div class="dialog-heading"><span class="board-kicker">From the workbench</span><h2 id="project-title"></h2><p></p></div><img class="original-project" alt=""><a class="project-source" target="_blank" rel="noopener noreferrer">View original Facebook project ↗</a>`;document.body.append(dialog);
function open(id){const p=projects.find(p=>p.id===id);if(!p)return;dialog.querySelector('h2').textContent=p.title;dialog.querySelector('p').textContent=p.note;const image=dialog.querySelector('img');image.src='assets/projects/'+p.original;image.alt=p.title+' — '+(id==='bathroom'?'before, during and after':'before and after');dialog.querySelector('a').href=p.source;dialog.showModal();document.body.classList.add('photo-open')}
function close(){dialog.close()}dialog.querySelector('button').onclick=close;dialog.addEventListener('close',()=>document.body.classList.remove('photo-open'));dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-project]');if(b)open(b.dataset.project)});
const scene=document.querySelector('.toolbox-scene');new MutationObserver(()=>{const ready=scene.classList.contains('present');board.hidden=!ready;document.body.classList.toggle('workshop-ready',ready)}).observe(scene,{attributes:true,attributeFilter:['class']});
window.HesterProjects={cards};
})();