(()=>{'use strict';
const projects=[{id:'bathroom',title:'Bathroom refresh',detail:'Panelling & painting',note:'From a blank wall to a room with character.',source:'https://www.facebook.com/photo.php?fbid=1611392387663830',original:'bathroom.jpg'},{id:'garden',title:'Garden tidy-up',detail:'Home & garden maintenance',note:'A little care. Room to enjoy the garden again.',source:'https://www.facebook.com/photo.php?fbid=1624609679675434',original:'garden.jpg'}];
const cards=projects.map((p,i)=>`<button class="project-print print-${i}" data-project="${p.id}" aria-label="View ${p.title} before and after"><span class="paper-tape" aria-hidden="true"></span><span class="photo-pair"><span><img src="assets/projects/${p.id}-before.jpg" alt="${p.title} before the work" loading="lazy" width="520" height="620"><b>Before</b></span><span><img src="assets/projects/${p.id}-after.jpg" alt="${p.title} after the work" loading="lazy" width="520" height="620"><b>After</b></span></span><span class="print-caption"><strong>${p.title}</strong><small>${p.detail}</small><span class="view-mark" aria-hidden="true">↗</span></span></button>`).join('');
const dialog=document.createElement('dialog');dialog.className='project-dialog';dialog.setAttribute('aria-labelledby','project-title');dialog.innerHTML=`<button class="photo-close" aria-label="Close project photos">×</button><div class="dialog-heading"><span class="board-kicker">From the workbench</span><h2 id="project-title"></h2><p></p></div><img class="original-project" alt=""><a class="project-source" target="_blank" rel="noopener noreferrer">View original Facebook project ↗</a>`;document.body.append(dialog);
function open(id){const p=projects.find(p=>p.id===id);if(!p)return;dialog.querySelector('h2').textContent=p.title;dialog.querySelector('p').textContent=p.note;const image=dialog.querySelector('img');image.src='assets/projects/'+p.original;image.alt=p.title+' — '+(id==='bathroom'?'before, during and after':'before and after');dialog.querySelector('a').href=p.source;dialog.showModal();document.body.classList.add('photo-open')}
function close(){dialog.close()}dialog.querySelector('button').onclick=close;dialog.addEventListener('close',()=>document.body.classList.remove('photo-open'));dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-project]');if(b)open(b.dataset.project)});
const videoUrl='https://www.facebook.com/reel/1807336213948529/';
const videoCard=`<button class="project-video-card" data-project="bathroom-video" aria-label="Play Hester Home Services bathroom project video"><span class="video-preview"><img src="assets/projects/bathroom-after.jpg" alt="Completed bathroom panelling and painting" loading="lazy"><span class="video-play" aria-hidden="true">▶</span></span><span><strong>See the work in motion</strong><small>Winter availability · Hester Home Services</small></span></button>`;
const videoDialog=document.createElement('dialog');videoDialog.className='project-dialog video-dialog';videoDialog.setAttribute('aria-labelledby','video-title');videoDialog.innerHTML=`<button class="photo-close" aria-label="Close project video">×</button><div class="dialog-heading"><span class="board-kicker">Hester Home Services</span><h2 id="video-title">The bathroom project</h2></div><div class="video-embed"></div><a class="project-source" href="${videoUrl}" target="_blank" rel="noopener noreferrer">Watch the original video on Facebook ↗</a>`;document.body.append(videoDialog);
function openVideo(){const frame=document.createElement('iframe');frame.src='https://www.facebook.com/plugins/video.php?href='+encodeURIComponent(videoUrl)+'&show_text=false&width=320';frame.title='Hester Home Services winter availability project video';frame.allow='autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';videoDialog.querySelector('.video-embed').replaceChildren(frame);videoDialog.showModal();document.body.classList.add('photo-open')}
videoDialog.querySelector('button').onclick=()=>videoDialog.close();videoDialog.addEventListener('close',()=>{videoDialog.querySelector('.video-embed').replaceChildren();document.body.classList.remove('photo-open')});document.addEventListener('click',e=>{if(e.target.closest('[data-project="bathroom-video"]'))openVideo()});
window.HesterProjects={cards:cards+videoCard};
})();